heysaiyad/dev-toolkit

index.html
tools/password-generator/README.md
tools/password-generator/index.html
tools/password-generator/script.js
tools/password-generator/style.css
tools/unix-timestamp-converter/README.md
tools/unix-timestamp-converter/index.html
tools/unix-timestamp-converter/script.js
tools/unix-timestamp-converter/style.css

Added a new feature that generates password based on the user inputs like length, include/exclude uppercases, numbers and special characters.
Fixes #: #28
(Please add a screenshot of your new tool or UI change)

feat: Add Password Generator

---

mise.toml

Added the mise.toml file to facilitate launching the application locally or in other environments.
Cf issue #45 if you think it's interesting
Fixes #: 45
Tell me if you think something is missing.

Add "mise.toml" to simplify project setup

---

CONTRIBUTING.md

Fixed #61:
📷 New Section: "Creating Quality Screenshots and GIFs"
The new section includes:
📸 Screenshot Guidelines
Technical specifications (resolution, browser settings, formats)
Desktop and mobile requirements with specific dimensions
Content guidelines for what to capture
Pre-screenshot checklist for consistency
🎬 GIF Creation Guidelines
When to create GIFs (workflows, animations, demonstrations)
Technical specs (duration, frame rate, file size limits)
Recommended tools (free and paid options)
Recording best practices with actionable tips
🖼️ File Organization
Naming conventions for consistency
File structure recommendations
Filename examples for different types of visuals
📋 Visual Documentation Checklist
Required vs optional screenshots
Technical quality standards
Content guidelines …

Modified CONTRIBUTING.md

---

index.html
tools/code-beautifier/index.html
tools/code-beautifier/script.js

This PR introduces a brand-new Code Beautifier to the DevToolkit! 🎉
Now, you can simply paste your messy or unformatted HTML code, and the tool will instantly clean it up, giving you nicely structured and easy-to-read code with proper indentation.
Fixes #17

Added code beautifier

---

index.html
script.js
style.css

Implemented a fixed, responsive sidebar navigation with categorized tools, built-in search, and contribution link. Enhanced the sticky header with glassmorphism, scroll effects, and a sidebar toggle. Added smart responsive design for desktop, tablet, and mobile with overlay behavior, keyboard shortcuts, and adaptive search. Improved user experience through accessibility features, smooth animations, and performance optimizations.
Fixes #39

Added sidebar and fixed to navbar

---

index.html
tools/percentage-calculator/index.html
tools/percentage-calculator/script.js

feat: Added Percentage Calculator tool
- Calculate the percentage of two numbers.
Follows TOOL_TEMPLATE.md guidelines and CONTRIBUTING.md requirements:
Fixes #: #74

feat: Added Percentage Calculator tool

---

index.html
tools/line-sorter-unique/index.html
tools/line-sorter-unique/script.js
tools/line-sorter-unique/style.css

Implemented Line Sorter/Unique Line Extractor
Fixes #: #31

Made Line Sorter/Unique Line Extractor

---

index.html
tools/even-odd-checker/index.html
tools/even-odd-checker/script.js

Added the Even Odd Checker Function
Fixes #: #73 
(Please add a screenshot of your new tool or UI change)

Added the Even Odd Checker Function

---

index.html
script.js

Please include a summary of the change and which issue is fixed.
Fixes #120

bugfix-tools-counter: update tools counter

---

style.css

fixing card behaviour
Fixes #118
https://github.com/user-attachments/assets/7e4b52b2-d98a-439d-a560-7a28e76e52da

fix_card_behaviour

---

script.js
style.css

Please include a summary of the change and which issue is fixed.
Fixes #102

bug-fix-active-filter-missing: Active Filter Button.

---

index.html
tools/text-repeater/index.html
tools/text-repeater/script.js

This PR adds a **Text Repeater Tool**.  
The tool allows users to input any text and choose how many times they want it repeated.  
It includes a clean Bootstrap-styled UI, copy-to-clipboard functionality, and responsive design.  
Fixes #37

 🔁 Text Repeater Tool

---

index.html
script.js
style.css

- Added a "Back to Top" button at the bottom-right corner of the page
Fixes #112

Add Back to Top button functionality

---

index.html
script.js
tools/xml-to-json-converter/index.html
tools/xml-to-json-converter/script.js

This PR add a tool to convert XML data to JSON data , and allow user to copy or download the JSON data
Fixes: #219

Feat: Xml to JSON converter

---

index.html
tools/json-yaml-converter/index.html
tools/json-yaml-converter/script.js

Feat: json-yaml and yam-json convertor
Fixes #192

feat json-yaml converter

---

index.html
tools/json-csv-converter/index.html
tools/json-csv-converter/script.js

Feat: simple json csv convertor
Fixes #154

json-csv-converter

---

index.html
tools/json-formatter/index.html
tools/json-formatter/script.js

This PR adds a **JSON Validator & Tree Viewer** tool.
Fixes #254 
<details>
<summary>Preview Gif</summary>
</details>

Add json formatter

---

index.html
tools/emi-calculator/index.html
tools/emi-calculator/script.js

simple tool for emi calculator
Fixes #243

simple tool for emi calculator

---

index.html
tools/image-cropper/index.html
tools/image-cropper/script.js

New tool for add an image cropper
Fixes #: #98

Add the new component image cropper

---

index.html
tools/aspect-ratio-calculator/README.md
tools/aspect-ratio-calculator/index.html
tools/aspect-ratio-calculator/script.js

A professional tool to calculate dimensions based on aspect ratios. Perfect for responsive web design, video editing, screen specifications, and any project requiring precise dimensional calculations.
Fixes #: #240

feat: Create a Responsive Aspect Ratio Calculator

---

index.html
tools/csv-viewer/index.html
tools/csv-viewer/script.js

Develop a tool where users can paste CSV data, and it displays the data in a formatted, editable table. Basic editing (e.g., cell changes) and CSV export could be future enhancements.
Fixes #184

Csv viewer

---

index.html
tools/exif-remover/index.html
tools/exif-remover/script.js

Image Metadata (EXIF) Remover Tool
Features
EXIF removal: Strips metadata from uploaded images
Privacy protection: Removes GPS, camera settings, and other embedded data
Drag & drop: Upload via drag-and-drop or file picker
Preview: Shows original image and detected EXIF data
Progress: Visual progress during processing
Download: Download the cleaned image
Technical Implementation
Canvas-based: Uses HTML5 Canvas to redraw images without EXIF
Client-side: Runs entirely in the browser
Format support: JPEG, PNG, WebP, and other common formats
File size limit: 10MB
UI/UX
DevToolkit styling: Matches existing design system
Responsive: Works on desktop and mobile
Animations: Smooth transitions and feedback
Notifications: Success/error messages
Keyboard shortcuts: Ctrl+O for file upload, Escape to …

issue 278 solved successfully

---

index.html
script.js
tools/text-extractor/index.html
tools/text-extractor/scripts.js

Fixes #124 [TOOL] : OCR Tool for text extraction from PDF and images.

Issue #124 [Tool]: Added OCR-based Text extraction tool

---

cookie-manager/index.html
cookie-manager/script.js

Develop a tool that displays the cookies for the current website domain. It should allow users to view, add, edit, and delete cookies for testing and debugging purposes.
Fixes #258

simple Cookie Editor/Viewer

---

index.html
tools/relative-date/index.html
tools/relative-date/script.js

Implement a tool that takes a past or future date/time input and displays it in a human-readable relative format (e.g., '5 minutes ago', 'in 3 months', 'yesterday').
Fixes #174

Add a Relative Time Formatter

---

index.html
tools/color-palette-generator/index.html
tools/color-palette-generator/script.js

Implement a tool that generates a harmonious color palette (e.g., 5 colors) based on a single input color, or by choosing a color harmony rule (e.g., monochromatic, analogous).
Fixes #177

simple Color Palette Generator

---

index.html
tools/text-to-ascii-converter/index.html
tools/text-to-ascii-converter/script.js

Tool: Text to ASCII Converter
A versatile text to ASCII value converter supporting multiple output formats including decimal, hexadecimal, binary, and octal representations.
Features
- Real-time conversion as you type
- Multiple format support (Decimal, Hex, Binary, Octal)
- Live statistics (character count, word count, min/max ASCII)
- One-click copy to clipboard
- Smooth animations and transitions
- Fully responsive design
Fixes #139

Text to Ascii Converter
